export const DRAFT_STATUS = {
  NEW: 'STATUS_NEW',
  ACTIVE: 'STATUS_ACTIVE',
  IDLE: 'STATUS_IDLE',
  RESUMED: 'STATUS_RESUMED',
  VALIDATING: 'STATUS_VALIDATING',
  SUBMITTING: 'STATUS_SUBMITTING',
  SUBMITTED: 'STATUS_SUBMITTED',
  EXPIRED: 'STATUS_EXPIRED',
  PURGED: 'STATUS_PURGED'
};
