export const ERROR_CODES = {
  ERR_LOCK_LOST: 'ERR_LOCK_LOST',
  ERR_DUPLICATE: 'ERR_DUPLICATE',
  ERR_JSON_TOO_LARGE: 'ERR_JSON_TOO_LARGE',
  ERR_SESSION_EXPIRED: 'ERR_SESSION_EXPIRED',
  ERR_RATE_LIMIT: 'ERR_RATE_LIMIT',
  ERR_LOOKUP_TIMEOUT: 'ERR_LOOKUP_TIMEOUT'
};
