export const EVENT_TYPES = {
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_RESUMED: 'SESSION_RESUMED',
  FIELD_UPDATED: 'FIELD_UPDATED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UPLOAD_STARTED: 'UPLOAD_STARTED',
  UPLOAD_COMPLETED: 'UPLOAD_COMPLETED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
  NETWORK_ONLINE: 'NETWORK_ONLINE',
  TAB_HIDDEN: 'TAB_HIDDEN',
  TAB_VISIBLE: 'TAB_VISIBLE',
  LOCK_LOST: 'LOCK_LOST',
  SUBMISSION_COMPLETED: 'SUBMISSION_COMPLETED'
};
