export const FRICTION_STAGES = {
  TEAM_DETAILS: 'STAGE_TEAM_DETAILS',
  LOGO_UPLOAD: 'STAGE_LOGO_UPLOAD',
  CAPTAIN_INFO: 'STAGE_CAPTAIN_INFO',
  PLAYER_2: 'STAGE_PLAYER_2',
  PLAYER_3: 'STAGE_PLAYER_3',
  PLAYER_4: 'STAGE_PLAYER_4',
  PLAYER_5: 'STAGE_PLAYER_5',
  REVIEW: 'STAGE_REVIEW',
  SUBMIT: 'STAGE_SUBMIT'
};
